spring:
  datasource:    username: root
    password: 200911
    url: jdbc:mysql://localhost:3306/test?useSSL=false&amp;serverTimezone=GMT%2B8&amp;allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置
    mybatis:
      mapper_location:classpath:mapper/*.xml
      type-aliases-package:com.example.demo.mapper